import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791070518112 implements MigrationInterface {
    name = 'InitialSchema1791070518112'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'captured', 'released', 'refunded', 'partially_refunded', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'EGP', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "gateway_name" character varying(30), "gateway_transaction_id" character varying, "kashier_transaction_id" character varying, "gateway_order_id" character varying, "gateway_session_id" character varying, "gateway_response" jsonb, "is_cash" boolean NOT NULL DEFAULT false, "captured_at" TIMESTAMP WITH TIME ZONE, "released_at" TIMESTAMP WITH TIME ZONE, "refunded_at" TIMESTAMP WITH TIME ZONE, "refund_amount" numeric(10,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e86edf76dc2424f123b9023a2b2" UNIQUE ("booking_id"), CONSTRAINT "REL_e86edf76dc2424f123b9023a2b" UNIQUE ("booking_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ad3c43e0487e4036cf8b357e0" ON "payments"  ("gateway_order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_paymentmethod_enum" AS ENUM('cash', 'card', 'vodafone_cash', 'instapay', 'fawry')`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending_payment', 'pending_driver_approval', 'confirmed', 'in_progress', 'trip_completed', 'cancelled_by_passenger', 'cancelled_by_driver', 'disputed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "passenger_id" uuid NOT NULL, "seats_count" smallint NOT NULL DEFAULT '1', "total_amount" numeric(10,2) NOT NULL, "commission_amount" numeric(10,2) NOT NULL DEFAULT '0', "driver_payout_amount" numeric(10,2) NOT NULL DEFAULT '0', "promo_discount_amount" numeric(10,2) NOT NULL DEFAULT '0', "commission_rate" numeric(5,4) NOT NULL, "paymentMethod" "public"."bookings_paymentmethod_enum" NOT NULL DEFAULT 'cash', "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending_driver_approval', "confirmed_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "driver_confirmed_completion" boolean NOT NULL DEFAULT false, "passenger_confirmed_completion" boolean NOT NULL DEFAULT false, "auto_confirm_after" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" character varying, "dispute_id" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_69c77e109ad6f822115013a440" ON "bookings"  ("passenger_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_edbfb04e162d66f308cbfdcd85" ON "bookings"  ("trip_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."trips_status_enum" AS ENUM('scheduled', 'active', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "origin_city" character varying(100) NOT NULL, "origin_address" character varying, "origin_lat" numeric(10,7), "origin_lng" numeric(10,7), "destination_city" character varying(100) NOT NULL, "destination_address" character varying, "destination_lat" numeric(10,7), "destination_lng" numeric(10,7), "departure_time" TIMESTAMP WITH TIME ZONE NOT NULL, "estimated_arrival_time" TIMESTAMP WITH TIME ZONE, "total_seats" smallint NOT NULL, "available_seats" smallint NOT NULL, "price_per_seat" numeric(10,2) NOT NULL, "status" "public"."trips_status_enum" NOT NULL DEFAULT 'scheduled', "women_only" boolean NOT NULL DEFAULT false, "smoking_allowed" boolean NOT NULL DEFAULT false, "pets_allowed" boolean NOT NULL DEFAULT false, "air_conditioning" boolean NOT NULL DEFAULT false, "luggage_size" character varying(20) NOT NULL DEFAULT 'medium', "chat_preference" character varying(20) NOT NULL DEFAULT 'friendly', "notes" text, "community_id" character varying, "current_lat" numeric(10,7), "current_lng" numeric(10,7), "tracking_updated_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" character varying, "reminder_sent_at" TIMESTAMP WITH TIME ZONE, "final_warning_sent_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f71c231dee9c05a9522f9e840f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb21893a7f1fc172eb700338e8" ON "trips"  ("origin_city") `);
        await queryRunner.query(`CREATE INDEX "IDX_e54fbb0bda09528c7736f76b0a" ON "trips"  ("destination_city") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6d04660d3fdca25c3dc6af71f" ON "trips"  ("departure_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_78c3553e8f1d77090ee7ed2526" ON "trips"  ("status", "departure_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_b51531c955f6bef583346ee445" ON "trips"  ("driver_id", "departure_time") `);
        await queryRunner.query(`CREATE TYPE "public"."ratings_rater_role_enum" AS ENUM('driver', 'passenger')`);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" character varying NOT NULL, "booking_id" character varying NOT NULL, "rater_id" uuid NOT NULL, "ratee_id" uuid NOT NULL, "rater_role" "public"."ratings_rater_role_enum" NOT NULL, "score" smallint NOT NULL, "comment" text, "is_revealed" boolean NOT NULL DEFAULT false, "reveal_after" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f65a88cfc9288dd846f9ed82e4" ON "ratings"  ("trip_id", "rater_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a97240e3a4cced7e5239745070" ON "ratings"  ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01ff3379190e9aad078492c231" ON "ratings"  ("ratee_id", "is_revealed") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_wallet_transaction_type_enum" AS ENUM('commission_credit', 'cash_commission_debit', 'withdrawal', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "driver_wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "balance" numeric(12,2) NOT NULL DEFAULT '0', "cash_commission_balance" numeric(12,2) NOT NULL DEFAULT '0', "transaction_type" "public"."driver_wallet_transaction_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "booking_id" character varying, "notes" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_349e94197daace215703557b144" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('passenger', 'driver', 'both', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('pending_verification', 'active', 'suspended', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone_number" character varying(20) NOT NULL, "full_name" character varying(100) NOT NULL, "profile_photo_url" character varying, "gender" "public"."users_gender_enum", "role" "public"."users_role_enum" NOT NULL DEFAULT 'passenger', "status" "public"."users_status_enum" NOT NULL DEFAULT 'pending_verification', "national_id_number" character varying(14), "national_id_photo_url" character varying, "id_verified" boolean NOT NULL DEFAULT false, "id_verified_at" TIMESTAMP WITH TIME ZONE, "driving_licence_number" character varying(20), "driving_licence_photo_url" character varying, "vehicle_make" character varying(50), "vehicle_model" character varying(50), "vehicle_year" smallint, "vehicle_color" character varying(30), "vehicle_plate" character varying(20), "vehicle_photo_url" character varying, "driver_verified" boolean NOT NULL DEFAULT false, "rating_average" numeric(3,2) NOT NULL DEFAULT '0', "rating_count" integer NOT NULL DEFAULT '0', "completed_trips_as_driver" integer NOT NULL DEFAULT '0', "cancelled_trips_as_driver" integer NOT NULL DEFAULT '0', "completed_trips_as_passenger" integer NOT NULL DEFAULT '0', "trust_flagged" boolean NOT NULL DEFAULT false, "dispute_count" integer NOT NULL DEFAULT '0', "emergency_contact_name" character varying(100), "emergency_contact_phone" character varying(20), "allows_smoking" boolean NOT NULL DEFAULT false, "allows_pets" boolean NOT NULL DEFAULT false, "referral_code" character varying(10), "referred_by_user_id" character varying, "promo_balance" numeric(10,2) NOT NULL DEFAULT '0', "points_balance" integer NOT NULL DEFAULT '0', "cancellation_strikes" integer NOT NULL DEFAULT '0', "cash_booking_restricted_until" TIMESTAMP WITH TIME ZONE, "trip_posting_banned_until" TIMESTAMP WITH TIME ZONE, "fcm_token" character varying, "preferred_language" character varying(5) NOT NULL DEFAULT 'ar', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ba10055f9ef9690e77cf6445cba" UNIQUE ("referral_code"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_17d1817f241f10a3dbafb169fd" ON "users"  ("phone_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dd7b9b43617dfec3cdd25ba20" ON "users"  ("national_id_number") `);
        await queryRunner.query(`CREATE TYPE "public"."disputes_reason_enum" AS ENUM('no_show_driver', 'no_show_passenger', 'unsafe_driving', 'wrong_route', 'payment_mismatch', 'harassment', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('open', 'under_review', 'resolved_refund', 'resolved_release', 'resolved_split', 'closed')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" character varying NOT NULL, "trip_id" character varying NOT NULL, "opened_by_user_id" uuid NOT NULL, "reason" "public"."disputes_reason_enum" NOT NULL, "description" text NOT NULL, "evidence_urls" jsonb, "other_party_response" text, "other_party_evidence_urls" jsonb, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'open', "assigned_admin_id" character varying, "resolution_notes" text, "refund_amount" numeric(10,2), "resolved_at" TIMESTAMP WITH TIME ZONE, "sla_deadline" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5040a286dd3794411fa151b509" ON "disputes"  ("status", "sla_deadline") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_722d6e06d51e51095ef73df20d" ON "disputes"  ("booking_id") `);
        await queryRunner.query(`CREATE TABLE "otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone_number" character varying(20) NOT NULL, "code" character varying(6) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "attempts" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f7aa837cc30b5f0a9bbb28c31" ON "otps"  ("phone_number") `);
        await queryRunner.query(`CREATE TABLE "platform_config" ("key" character varying(100) NOT NULL, "value" text NOT NULL, "description" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e288d39f7103fdc2a057f96b62e" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "trip_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f053370498ff61658917241d211" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f583fee0a8f12a1b439673046" ON "trip_locations"  ("trip_id", "recorded_at") `);
        await queryRunner.query(`CREATE TABLE "trip_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" character varying NOT NULL, "user_id" uuid NOT NULL, "body" character varying(500) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_22ad2ffed64f47a449791fa3ff1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eac191f0fd65fbbdb9009e9cab" ON "trip_comments"  ("trip_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "trip_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" character varying NOT NULL, "sender_id" uuid NOT NULL, "body" character varying(1000) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7ff74e17236f408922537c8d747" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c49c9680f2dab9b4dc6fbec1d" ON "trip_messages"  ("trip_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."withdrawal_requests_payout_method_enum" AS ENUM('vodafone_cash', 'instapay', 'bank')`);
        await queryRunner.query(`CREATE TYPE "public"."withdrawal_requests_status_enum" AS ENUM('pending', 'paid', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "withdrawal_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "payout_method" "public"."withdrawal_requests_payout_method_enum" NOT NULL, "payout_account" character varying(50) NOT NULL, "status" "public"."withdrawal_requests_status_enum" NOT NULL DEFAULT 'pending', "admin_note" character varying, "payout_name" character varying, "payout_bank" character varying, "kashier_transfer_id" character varying, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e1b3734a3f3cbd46bf0ad7eedb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7b4c82f283337e65892002e3b" ON "withdrawal_requests"  ("driver_id", "status") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "title" character varying(200) NOT NULL, "body" character varying(1000) NOT NULL, "data" jsonb, "read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_created" ON "notifications"  ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "referral_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referrer_id" character varying NOT NULL, "referred_user_id" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_5709a5dd9caeb9a86826022e5cc" UNIQUE ("referred_user_id"), CONSTRAINT "PK_a3be1dc8ab03f052b59d8aefbad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_hash" ON "refresh_tokens"  ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "blocker_id" uuid NOT NULL, "blocked_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_806f6a5d38d031cdd868fd5e37e" UNIQUE ("blocker_id", "blocked_id"), CONSTRAINT "PK_8244fa1495c4e9222a01059244b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'cancelled', 'past_due', 'trialing')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "current_period_end" TIMESTAMP WITH TIME ZONE, "renewal_reminder_sent_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d0a95ef8a28188364c546eb65c1" UNIQUE ("user_id"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sos_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "trip_id" character varying, "lat" numeric(10,7), "lng" numeric(10,7), "message" text, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5c6f2f5f40ab2224315e007b9c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6fce40127ed3bc20d1ad99aaaa" ON "sos_alerts"  ("resolved_at", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_payments_status_enum" AS ENUM('pending', 'paid', 'failed')`);
        await queryRunner.query(`CREATE TABLE "subscription_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "period_days" smallint NOT NULL, "status" "public"."subscription_payments_status_enum" NOT NULL DEFAULT 'pending', "merchant_order_id" character varying(64) NOT NULL, "gateway_session_id" character varying, "kashier_order_id" character varying, "kashier_transaction_id" character varying, "paid_at" TIMESTAMP WITH TIME ZONE, "period_start" TIMESTAMP WITH TIME ZONE, "period_end" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1b7a76365fd477de59cba0ab957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f230ad906ef1708f7085665980" ON "subscription_payments"  ("merchant_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8c12bf0637939e745ca37f891" ON "subscription_payments"  ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_1a764d454e20296cfa277d8742e" FOREIGN KEY ("passenger_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_a5f23ba85e0f0d183b0a57476a8" FOREIGN KEY ("rater_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_ac3ffaae03462c3e46a39e84caf" FOREIGN KEY ("ratee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_wallet" ADD CONSTRAINT "FK_64ef5c4e88e49f6b18e5553df9b" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_cc3828e0c45f7f25f5d9c8a1ef5" FOREIGN KEY ("opened_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_locations" ADD CONSTRAINT "FK_f2f143ae23d7d65d7bb57e2c387" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_comments" ADD CONSTRAINT "FK_d5649c7cc560e48efc6df850fec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_messages" ADD CONSTRAINT "FK_9f68cf624dea9b8201894c97117" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" ADD CONSTRAINT "FK_23c850a1ccc75383d9ce288736a" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocks" ADD CONSTRAINT "FK_74f530c6fbffc357047b263818d" FOREIGN KEY ("blocker_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocks" ADD CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0" FOREIGN KEY ("blocked_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sos_alerts" ADD CONSTRAINT "FK_7a5209ca217c11fd1c5767d1450" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sos_alerts" DROP CONSTRAINT "FK_7a5209ca217c11fd1c5767d1450"`);
        await queryRunner.query(`ALTER TABLE "blocks" DROP CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0"`);
        await queryRunner.query(`ALTER TABLE "blocks" DROP CONSTRAINT "FK_74f530c6fbffc357047b263818d"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "withdrawal_requests" DROP CONSTRAINT "FK_23c850a1ccc75383d9ce288736a"`);
        await queryRunner.query(`ALTER TABLE "trip_messages" DROP CONSTRAINT "FK_9f68cf624dea9b8201894c97117"`);
        await queryRunner.query(`ALTER TABLE "trip_comments" DROP CONSTRAINT "FK_d5649c7cc560e48efc6df850fec"`);
        await queryRunner.query(`ALTER TABLE "trip_locations" DROP CONSTRAINT "FK_f2f143ae23d7d65d7bb57e2c387"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_cc3828e0c45f7f25f5d9c8a1ef5"`);
        await queryRunner.query(`ALTER TABLE "driver_wallet" DROP CONSTRAINT "FK_64ef5c4e88e49f6b18e5553df9b"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_ac3ffaae03462c3e46a39e84caf"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_a5f23ba85e0f0d183b0a57476a8"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_1a764d454e20296cfa277d8742e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8c12bf0637939e745ca37f891"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f230ad906ef1708f7085665980"`);
        await queryRunner.query(`DROP TABLE "subscription_payments"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fce40127ed3bc20d1ad99aaaa"`);
        await queryRunner.query(`DROP TABLE "sos_alerts"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "blocks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_hash"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "referral_rewards"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_created"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7b4c82f283337e65892002e3b"`);
        await queryRunner.query(`DROP TABLE "withdrawal_requests"`);
        await queryRunner.query(`DROP TYPE "public"."withdrawal_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."withdrawal_requests_payout_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c49c9680f2dab9b4dc6fbec1d"`);
        await queryRunner.query(`DROP TABLE "trip_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eac191f0fd65fbbdb9009e9cab"`);
        await queryRunner.query(`DROP TABLE "trip_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f583fee0a8f12a1b439673046"`);
        await queryRunner.query(`DROP TABLE "trip_locations"`);
        await queryRunner.query(`DROP TABLE "platform_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f7aa837cc30b5f0a9bbb28c31"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_722d6e06d51e51095ef73df20d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5040a286dd3794411fa151b509"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dd7b9b43617dfec3cdd25ba20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17d1817f241f10a3dbafb169fd"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TABLE "driver_wallet"`);
        await queryRunner.query(`DROP TYPE "public"."driver_wallet_transaction_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01ff3379190e9aad078492c231"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a97240e3a4cced7e5239745070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f65a88cfc9288dd846f9ed82e4"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP TYPE "public"."ratings_rater_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b51531c955f6bef583346ee445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78c3553e8f1d77090ee7ed2526"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6d04660d3fdca25c3dc6af71f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e54fbb0bda09528c7736f76b0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb21893a7f1fc172eb700338e8"`);
        await queryRunner.query(`DROP TABLE "trips"`);
        await queryRunner.query(`DROP TYPE "public"."trips_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edbfb04e162d66f308cbfdcd85"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69c77e109ad6f822115013a440"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_paymentmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ad3c43e0487e4036cf8b357e0"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
    }

}
