// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7bNoeWJ400_djr6Pxt6LI0mfslIwr68',
    appId: '1:341297849403:web:f23a87965b5a474f86e81e',
    messagingSenderId: '341297849403',
    projectId: 'yala-nsafr',
    authDomain: 'yala-nsafr.firebaseapp.com',
    storageBucket: 'yala-nsafr.firebasestorage.app',
    measurementId: 'G-MGEHMJTYHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMUn0FJm80LSXP1aAJBg0q2Bf4Z-kDsk',
    appId: '1:341297849403:android:e6d17e7b924d699c86e81e',
    messagingSenderId: '341297849403',
    projectId: 'yala-nsafr',
    storageBucket: 'yala-nsafr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBbiMW1x7TgxbN9dZQw_snc-DKhV8Pfc',
    appId: '1:341297849403:ios:851ad4ee86aeaf3486e81e',
    messagingSenderId: '341297849403',
    projectId: 'yala-nsafr',
    storageBucket: 'yala-nsafr.firebasestorage.app',
    iosBundleId: 'com.yalansafr.yalaNsafr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBbiMW1x7TgxbN9dZQw_snc-DKhV8Pfc',
    appId: '1:341297849403:ios:851ad4ee86aeaf3486e81e',
    messagingSenderId: '341297849403',
    projectId: 'yala-nsafr',
    storageBucket: 'yala-nsafr.firebasestorage.app',
    iosBundleId: 'com.yalansafr.yalaNsafr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX7bNoeWJ400_djr6Pxt6LI0mfslIwr68',
    appId: '1:341297849403:web:9dec180b6abbaf6486e81e',
    messagingSenderId: '341297849403',
    projectId: 'yala-nsafr',
    authDomain: 'yala-nsafr.firebaseapp.com',
    storageBucket: 'yala-nsafr.firebasestorage.app',
    measurementId: 'G-EJG90BCHYP',
  );
}
